name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      database:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v7
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '29.0'
        elixir-version: '1.20.4'
    - uses: actions/setup-node@v4
      with:
        node-version: '26'
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix assets.setup
        mix assets.build
    - name: Run Tests
      run: mix test
