name: Elixir CI

on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    services:
      database:
        image: mysql@sha256:85b9bf2e29cf836ecb8c2a15a935d4ba0c606631dff1dd79531a11983c638f2a # 8
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
        otp-version: '29.0'
        elixir-version: '1.20.4'
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '26'
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix assets.setup
        mix assets.build
    - name: Run Tests
      run: mix test

  zizmor:
    name: Zizmor (workflow SAST)

    runs-on: ubuntu-latest

    permissions:
      security-events: write # required to upload zizmor's SARIF results
      contents: read # required to check out the repository
      actions: read # required to read the list of workflows to scan

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
